In [1]:
import numpy as np

In [2]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a1 = np.array(A[1,:])
a1

array([4, 5, 6])

In [5]:
A_up_down = np.vstack([a1,A,a1])
A_up_down

array([[4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]])

In [7]:
b1 = np.array(A_up_down[:,1]).reshape(len(A_up_down),1)

In [8]:
b1

array([[5],
       [2],
       [5],
       [8],
       [5]])

In [9]:
A_all_dir = np.hstack([b1,A_up_down,b1])
A_all_dir

array([[5, 4, 5, 6, 5],
       [2, 1, 2, 3, 2],
       [5, 4, 5, 6, 5],
       [8, 7, 8, 9, 8],
       [5, 4, 5, 6, 5]])