In [3]:
import numpy as np

In [4]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1 = np.array(A[1,:])
a1

array([4, 5, 6])

In [6]:
A_up_down = np.vstack([a1,A,a1])
A_up_down

array([[4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]])

In [7]:
b1 = np.array(A_up_down[:,1]).reshape(len(A_up_down),1)

In [8]:
b1

array([[5],
       [2],
       [5],
       [8],
       [5]])

In [9]:
A_all_dir = np.hstack([b1,A_up_down,b1])
A_all_dir

array([[5, 4, 5, 6, 5],
       [2, 1, 2, 3, 2],
       [5, 4, 5, 6, 5],
       [8, 7, 8, 9, 8],
       [5, 4, 5, 6, 5]])

In [10]:
def mirror_matrix(A, fil):
    pad = int((fil-1)/2)
    for i in range(1,pad+1): # up_down and left_right
        up_down = np.array(A[2*i-1,:])
        Matrix_up_down = np.vstack([up_down,A,up_down])
        left_right = np.array(Matrix_up_down[:,2*i-1]).reshape(len(Matrix_up_down),1)
        Matrix_left_right = np.hstack([left_right,Matrix_up_down,left_right])
        A = Matrix_left_right
    return A

In [24]:
B = np.arange(1,37).reshape(6,6)
B

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [21]:
mirror_matrix(B,3)

array([[ 7,  6,  7,  8,  9, 10, 11,  7],
       [ 1,  0,  1,  2,  3,  4,  5,  1],
       [ 7,  6,  7,  8,  9, 10, 11,  7],
       [13, 12, 13, 14, 15, 16, 17, 13],
       [19, 18, 19, 20, 21, 22, 23, 19],
       [25, 24, 25, 26, 27, 28, 29, 25],
       [31, 30, 31, 32, 33, 34, 35, 31],
       [ 7,  6,  7,  8,  9, 10, 11,  7]])

In [ ]:
def mirror_matrix_rectangle(A, fil):
    pad = int((fil-1)/2)
    for i in range(1,pad+1): # up_down and left_right
        up_down = np.array(A[2*i-1,:])
        Matrix_up_down = np.vstack([up_down,A,up_down])
        left_right = np.array(Matrix_up_down[:,2*i-1]).reshape(len(Matrix_up_down),1)
        Matrix_left_right = np.hstack([left_right,Matrix_up_down,left_right])
        A = Matrix_left_right
    return A

In [35]:
C = np.arange(1,37).reshape(6,6)
C

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [36]:
c1 = C[1,:]
c1

array([ 7,  8,  9, 10, 11, 12])

In [37]:
c2 = C[-2,:]
c2

array([25, 26, 27, 28, 29, 30])

In [38]:
D = np.vstack([c1,C,c2])
D

array([[ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [25, 26, 27, 28, 29, 30]])

In [53]:
d1 = D[:,1]
d2 = D[:,-2]

In [54]:
d1

array([ 8,  2,  8, 14, 20, 26, 32, 26])

In [55]:
d2

array([11,  5, 11, 17, 23, 29, 35, 29])

In [56]:
d1 = d1.reshape(len(D),1)

In [57]:
d2 = d2.reshape(len(D),1)

In [58]:
d1

array([[ 8],
       [ 2],
       [ 8],
       [14],
       [20],
       [26],
       [32],
       [26]])

In [59]:
d2

array([[11],
       [ 5],
       [11],
       [17],
       [23],
       [29],
       [35],
       [29]])

In [60]:
D_ = np.hstack([d1,D,d2])
D_

array([[ 8,  7,  8,  9, 10, 11, 12, 11],
       [ 2,  1,  2,  3,  4,  5,  6,  5],
       [ 8,  7,  8,  9, 10, 11, 12, 11],
       [14, 13, 14, 15, 16, 17, 18, 17],
       [20, 19, 20, 21, 22, 23, 24, 23],
       [26, 25, 26, 27, 28, 29, 30, 29],
       [32, 31, 32, 33, 34, 35, 36, 35],
       [26, 25, 26, 27, 28, 29, 30, 29]])

In [61]:
def mirror_matrix(A, fil):
    pad = int((fil-1)/2)
    for  i in range(1,pad+1):
        up = np.array(A[2*i-1,:])
        down = np.array(A[-2*i,:])
        Matrix_up_down = np.vstack([up,A,down])
        left = np.array(Matrix_up_down[:,2*i-1]).reshape(len(Matrix_up_down),1)
        right = np.array(Matrix_up_down[:,-2*i]).reshape(len(Matrix_up_down),1)
        Matrix_left_right = np.hstack([left,Matrix_up_down,right,])
        A = Matrix_left_right
    return A
        

In [62]:
B = np.arange(49).reshape(7,7)

In [66]:
B

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [68]:
test(B,7)

array([[24, 23, 22, 21, 22, 23, 24, 25, 26, 27, 26, 25, 24],
       [17, 16, 15, 14, 15, 16, 17, 18, 19, 20, 19, 18, 17],
       [10,  9,  8,  7,  8,  9, 10, 11, 12, 13, 12, 11, 10],
       [ 3,  2,  1,  0,  1,  2,  3,  4,  5,  6,  5,  4,  3],
       [10,  9,  8,  7,  8,  9, 10, 11, 12, 13, 12, 11, 10],
       [17, 16, 15, 14, 15, 16, 17, 18, 19, 20, 19, 18, 17],
       [24, 23, 22, 21, 22, 23, 24, 25, 26, 27, 26, 25, 24],
       [31, 30, 29, 28, 29, 30, 31, 32, 33, 34, 33, 32, 31],
       [38, 37, 36, 35, 36, 37, 38, 39, 40, 41, 40, 39, 38],
       [45, 44, 43, 42, 43, 44, 45, 46, 47, 48, 47, 46, 45],
       [38, 37, 36, 35, 36, 37, 38, 39, 40, 41, 40, 39, 38],
       [31, 30, 29, 28, 29, 30, 31, 32, 33, 34, 33, 32, 31],
       [24, 23, 22, 21, 22, 23, 24, 25, 26, 27, 26, 25, 24]])

In [71]:
C = np.arange(45).reshape(5,9)

In [72]:
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [75]:
test(C,3)

array([[10,  9, 10, 11, 12, 13, 14, 15, 16, 17, 16],
       [ 1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  7],
       [10,  9, 10, 11, 12, 13, 14, 15, 16, 17, 16],
       [19, 18, 19, 20, 21, 22, 23, 24, 25, 26, 25],
       [28, 27, 28, 29, 30, 31, 32, 33, 34, 35, 34],
       [37, 36, 37, 38, 39, 40, 41, 42, 43, 44, 43],
       [28, 27, 28, 29, 30, 31, 32, 33, 34, 35, 34]])

## 正确

In [ ]:
def test(A, fil):
    pad = int((fil-1)/2)
    for  i in range(1,pad+1):
        up = np.array(A[2*i-1,:])
        down = np.array(A[-2*i,:])
        Matrix_up_down = np.vstack([up,A,down])
        left = np.array(Matrix_up_down[:,2*i-1]).reshape(len(Matrix_up_down),1)
        right = np.array(Matrix_up_down[:,-2*i]).reshape(len(Matrix_up_down),1)
        Matrix_left_right = np.hstack([left,Matrix_up_down,right,])
        A = Matrix_left_right
    return A