In [2]:
import numpy as np

In [3]:
A = np.arange(1,26).reshape(5,5)

In [4]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
A[1,1]

7

In [7]:
a = np.array(A[1,:])

In [8]:
a

array([ 6,  7,  8,  9, 10])

In [11]:
C1 = np.vstack([a,A])
C1

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
b = np.array(C1[:,1]).reshape(len(C1),1)

In [19]:
b

array([[ 7],
       [ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [20]:
C2 = np.hstack([b,C1])
C2

array([[ 7,  6,  7,  8,  9, 10],
       [ 2,  1,  2,  3,  4,  5],
       [ 7,  6,  7,  8,  9, 10],
       [12, 11, 12, 13, 14, 15],
       [17, 16, 17, 18, 19, 20],
       [22, 21, 22, 23, 24, 25]])

In [22]:
c = np.array(C2[3,:])
c

array([12, 11, 12, 13, 14, 15])

In [23]:
C3 = np.vstack([c,C2])
C3

array([[12, 11, 12, 13, 14, 15],
       [ 7,  6,  7,  8,  9, 10],
       [ 2,  1,  2,  3,  4,  5],
       [ 7,  6,  7,  8,  9, 10],
       [12, 11, 12, 13, 14, 15],
       [17, 16, 17, 18, 19, 20],
       [22, 21, 22, 23, 24, 25]])

In [27]:
d = np.array(C3[:,3]).reshape(len(C3),1)
d

array([[13],
       [ 8],
       [ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [28]:
C4 = np.hstack([d,C3])

In [29]:
C4

array([[13, 12, 11, 12, 13, 14, 15],
       [ 8,  7,  6,  7,  8,  9, 10],
       [ 3,  2,  1,  2,  3,  4,  5],
       [ 8,  7,  6,  7,  8,  9, 10],
       [13, 12, 11, 12, 13, 14, 15],
       [18, 17, 16, 17, 18, 19, 20],
       [23, 22, 21, 22, 23, 24, 25]])