In [1]:
# 可以提取出高光谱数据的一个channel的数据 144*144
def split_one_channel(A ,channel):
    d = [0]*144
    for i in range(144):
        d[i] = input_image[i][:,channel-1]
    e = np.vstack((d[i] for i in range(144)))
    return e  
# 参数说明
# channel 通道
# A 高光谱立方块

In [2]:
# 依据patch大小（Filter 大小）对矩阵进行镜像处理
def mirror_matrix(A, fil):
    pad = int((fil-1)/2)
    for i in range(1,pad+1): # up_down and left_right
        up_down = np.array(A[2*i-1,:])
        Matrix_up_down = np.vstack([up_down,A,up_down])
        left_right = np.array(Matrix_up_down[:,2*i-1]).reshape(len(Matrix_up_down),1)
        Matrix_left_right = np.hstack([left_right,Matrix_up_down,left_right])
        A = Matrix_left_right
    return A

# 参数说明
# n   array size
# fil  filter size5*5
# pad = (fil-1)/2  padding大小

In [13]:
# 将镜像处理后的矩阵进行向量化操作
def split_array(A,fil):
    s = []
    length = len(A)-fil+1
    for i in range(length): # row
        for j in range(length): # col
            temp = [0]* fil
            for z in range(fil):
                temp[z] = A[i+z,j:j+fil]
            com = np.concatenate([item for item in temp ])
            s.append(com)
    return s 
# 参数说明
# A 镜像处理后的矩阵
# fil  filter size

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat
import spectral
from sklearn import preprocessing
import pandas as pd

In [15]:
input_image = loadmat('H:\data\hyp_data.mat')['hyp_data']
output_image = loadmat('H:\data\X.mat')['X']

In [16]:
origin_matrix_one = split_one_channel(input_image,1)  # 取出第1个channel的信息
mirror_matrix_one = mirror_matrix(origin_matrix_one,3) # 对第1个channel进行mirror操作
split_list = split_array(mirror_matrix_one,3)

In [17]:
mirror_matrix_one.shape

(146, 146)

In [19]:
split_list

[array([3515, 3344, 3515, 3348, 3172, 3348, 3515, 3344, 3515], dtype=uint16),
 array([3344, 3515, 3518, 3172, 3348, 3687, 3344, 3515, 3518], dtype=uint16),
 array([3515, 3518, 3686, 3348, 3687, 3517, 3515, 3518, 3686], dtype=uint16),
 array([3518, 3686, 3512, 3687, 3517, 3514, 3518, 3686, 3512], dtype=uint16),
 array([3686, 3512, 3341, 3517, 3514, 3343, 3686, 3512, 3341], dtype=uint16),
 array([3512, 3341, 3339, 3514, 3343, 3343, 3512, 3341, 3339], dtype=uint16),
 array([3341, 3339, 3173, 3343, 3343, 3343, 3341, 3339, 3173], dtype=uint16),
 array([3339, 3173, 3510, 3343, 3343, 3346, 3339, 3173, 3510], dtype=uint16),
 array([3173, 3510, 3165, 3343, 3346, 3522, 3173, 3510, 3165], dtype=uint16),
 array([3510, 3165, 3003, 3346, 3522, 3858, 3510, 3165, 3003], dtype=uint16),
 array([3165, 3003, 3510, 3522, 3858, 3514, 3165, 3003, 3510], dtype=uint16),
 array([3003, 3510, 3173, 3858, 3514, 3343, 3003, 3510, 3173], dtype=uint16),
 array([3510, 3173, 3512, 3514, 3343, 3343, 3510, 3173, 3512], d