In [2]:
import numpy as np

In [3]:
A = np.arange(1,26).reshape(5,5)

In [4]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
a1 = A[0,:3]
a2 = A[1,:3]
a3 = A[2,:3]
com1 = np.concatenate([a1,a2,a3])

In [6]:
a1
a2
a3

array([11, 12, 13])

In [7]:
com1

array([ 1,  2,  3,  6,  7,  8, 11, 12, 13])

In [8]:
b1 = A[0,1:4]
b2 = A[1,1:4]
b3 = A[2,1:4]
com2 = np.concatenate([b1,b2,b3])
com2

array([ 2,  3,  4,  7,  8,  9, 12, 13, 14])

In [9]:
b1

array([2, 3, 4])

In [10]:
c1 = A[0,2:5]
c2 = A[1,2:5]
c3 = A[2,2:5]
com3 = np.concatenate([c1,c2,c3])
com3

array([ 3,  4,  5,  8,  9, 10, 13, 14, 15])

In [11]:
d1 = A[2,0:3]
d2 = A[3,0:3]
d3 = A[4,0:3]
com4 = np.concatenate([d1,d2,d3])
com4

array([11, 12, 13, 16, 17, 18, 21, 22, 23])

In [12]:
fil = 3
def split_array(A,fil):
    s = []
    length = len(A)-fil+1
    for i in range(length): # row
        for j in range(length): # col
            temp = [0]* fil
            for z in range(fil):
                temp[z] = A[i+z,j:j+fil]
            com = np.concatenate([item for item in temp ])
            s.append(com)
    return s               

In [13]:
B = np.arange(36).reshape(6,6)

In [14]:
res = split_array(B,5)
res  

[array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 18, 19,
        20, 21, 22, 24, 25, 26, 27, 28]),
 array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20,
        21, 22, 23, 25, 26, 27, 28, 29]),
 array([ 6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25,
        26, 27, 28, 30, 31, 32, 33, 34]),
 array([ 7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26,
        27, 28, 29, 31, 32, 33, 34, 35])]

In [15]:
B

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
s1 = A[0,:3]
s2 = A[1,:3]
s3 = A[2,:3]

In [18]:
np.vstack([s1,s2,s3])

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [19]:
p1 = A[0,1:4]
p2 = A[1,1:4]
p3 = A[2,1:4]

In [20]:
np.vstack([p1,p2,p3])

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [40]:
def create_patch_one(A,fil):
    whole_arr = list()
    row = A.shape[0]-fil+1
    column = A.shape[1]-fil+1
    for i in range(row):
        for j in range(column):
            temp_arr = list()
            for z in range(fil):
                p = A[i+z,j:j+fil]
                temp_arr.append(p)
            one_arr = np.vstack(temp_arr)
            whole_arr.append(one_arr)
    return np.array(whole_arr)

In [43]:
create_patch_one(A,3)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
create_patch_one(A,3)

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]],

       [[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [ 8,  9, 10],
        [13, 14, 15]],

       [[ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]],

       [[ 8,  9, 10],
        [13, 14, 15],
        [18, 19, 20]],

       [[11, 12, 13],
        [16, 17, 18],
        [21, 22, 23]],

       [[12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]],

       [[13, 14, 15],
        [18, 19, 20],
        [23, 24, 25]]])

In [23]:
D = np.arange(50).reshape(5,5,2)
D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [24]:
D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [25]:
def create_patch_whole(A,fil,dim):
    temp = [create_patch_one(split_one_channel(A,i),fil) for i in range(1,dim+1)] # every dim do split_one_channel and combine
    temp_arr = np.array(temp)
    return temp_arr
    

In [46]:
def split_one_channel(A,channel):
    row = A.shape[0]
    d = [0]*row
    for i in range(row):
        d[i] = A[i][:,channel-1]
    e = np.vstack((d[i] for i in range(row)))
    return e 

In [47]:
split_one_channel(D,1)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [28]:
patch = create_patch_whole(D,3,2 )

In [29]:
patch

array([[[[ 0,  2,  4],
         [10, 12, 14],
         [20, 22, 24]],

        [[ 2,  4,  6],
         [12, 14, 16],
         [22, 24, 26]],

        [[ 4,  6,  8],
         [14, 16, 18],
         [24, 26, 28]],

        [[10, 12, 14],
         [20, 22, 24],
         [30, 32, 34]],

        [[12, 14, 16],
         [22, 24, 26],
         [32, 34, 36]],

        [[14, 16, 18],
         [24, 26, 28],
         [34, 36, 38]],

        [[20, 22, 24],
         [30, 32, 34],
         [40, 42, 44]],

        [[22, 24, 26],
         [32, 34, 36],
         [42, 44, 46]],

        [[24, 26, 28],
         [34, 36, 38],
         [44, 46, 48]]],


       [[[ 1,  3,  5],
         [11, 13, 15],
         [21, 23, 25]],

        [[ 3,  5,  7],
         [13, 15, 17],
         [23, 25, 27]],

        [[ 5,  7,  9],
         [15, 17, 19],
         [25, 27, 29]],

        [[11, 13, 15],
         [21, 23, 25],
         [31, 33, 35]],

        [[13, 15, 17],
         [23, 25, 27],
         [33, 35, 37]],

    

In [30]:
patch.shape  2 dim   9 patch nums   3x3 filter size

(2, 9, 3, 3)

In [32]:
patch[1].shape 

(9, 3, 3)

In [58]:
## patch[dim][patchnums_of_dim]  第二项最大为 n-f+1 -1 即filter后的大小
## reshape(2,3,3)  # 2 -- dim   # 3x3 fil   
np.vstack([patch[0][0],patch[1][0]]).reshape(2,3,3)  

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [39]:
np.vstack([patch[0][8],patch[1][8]]).reshape(2,3,3)

array([[[24, 26, 28],
        [34, 36, 38],
        [44, 46, 48]],

       [[25, 27, 29],
        [35, 37, 39],
        [45, 47, 49]]])

In [59]:
def create_patch_cube(patch,fil,dim):
    temp = list()
    nums = patch[0].shape[0] # the nums of every dim of windows  n - f + 1
    for j in range(nums):
        temp_re = np.vstack([patch[i][j] for i in range(dim)]).reshape(dim,fil,fil)
        temp_re1= temp_re.transpose(2,1,0) # switch 1,3 dim
        temp_re2 = temp_re1.transpose(1,0,2) # switch 1,2 dim
        temp.append(temp_re2)
    patch_cubes = np.array(temp)
    return patch_cubes

In [67]:
s = create_patch_cube(patch,3,2)
s.shape    # 9个patch tensor    each 3x3x3

(9, 3, 3, 2)

## test

In [61]:
s1 = s[0].transpose(2,1,0)

In [62]:
s1

array([[[ 0, 10, 20],
        [ 2, 12, 22],
        [ 4, 14, 24]],

       [[ 1, 11, 21],
        [ 3, 13, 23],
        [ 5, 15, 25]]])

In [63]:
s2 = s1.transpose(1,0,2)
s2

array([[[ 0, 10, 20],
        [ 1, 11, 21]],

       [[ 2, 12, 22],
        [ 3, 13, 23]],

       [[ 4, 14, 24],
        [ 5, 15, 25]]])

In [64]:
s2.shape

(3, 2, 3)

In [65]:
s.shape  # 9个patch-3d tensor  每个tensor 2x3x3

(9, 3, 3, 2)

## 转换坐标操作

In [110]:
create_patch_cube(patch,3,2).shape

(9, 2, 3, 3)

In [122]:
## transpose和swapaxes

In [125]:
S = np.arange(50).reshape(5,5,2)

In [126]:
S

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [134]:
S1 = S.transpose(2,1,0)
S1

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [138]:
S2 = S1.transpose(0,2,1)
S2.shape

(2, 5, 5)

In [142]:
S3 = S2.transpose(0,2,1)

In [144]:
S4 = S3.transpose(2,1,0)

In [145]:
S4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])