In [1]:
import numpy as np

In [2]:
A = np.arange(1,26).reshape(5,5)

In [3]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
a1 = A[0,:3]
a2 = A[1,:3]
a3 = A[2,:3]
com1 = np.concatenate([a1,a2,a3])

In [5]:
a1
a2
a3

array([11, 12, 13])

In [6]:
com1

array([ 1,  2,  3,  6,  7,  8, 11, 12, 13])

In [7]:
b1 = A[0,1:4]
b2 = A[1,1:4]
b3 = A[2,1:4]
com2 = np.concatenate([b1,b2,b3])
com2

array([ 2,  3,  4,  7,  8,  9, 12, 13, 14])

In [8]:
c1 = A[0,2:5]
c2 = A[1,2:5]
c3 = A[2,2:5]
com3 = np.concatenate([c1,c2,c3])
com3

array([ 3,  4,  5,  8,  9, 10, 13, 14, 15])

In [9]:
d1 = A[2,0:3]
d2 = A[3,0:3]
d3 = A[4,0:3]
com4 = np.concatenate([d1,d2,d3])
com4

array([11, 12, 13, 16, 17, 18, 21, 22, 23])

In [14]:
fil = 3
def split_array(A,fil):
    s = []
    for i in range(fil): # row
        for j in range(fil): # col
            temp = [0]* fil
            for z in range(fil):
                temp[z] = A[i+z,j:j+fil]
            com = np.concatenate([item for item in temp ])
            s.append(com)
    return s

res = split_array(A,3)
res  
                

[array([ 1,  2,  3,  6,  7,  8, 11, 12, 13]),
 array([ 2,  3,  4,  7,  8,  9, 12, 13, 14]),
 array([ 3,  4,  5,  8,  9, 10, 13, 14, 15]),
 array([ 6,  7,  8, 11, 12, 13, 16, 17, 18]),
 array([ 7,  8,  9, 12, 13, 14, 17, 18, 19]),
 array([ 8,  9, 10, 13, 14, 15, 18, 19, 20]),
 array([11, 12, 13, 16, 17, 18, 21, 22, 23]),
 array([12, 13, 14, 17, 18, 19, 22, 23, 24]),
 array([13, 14, 15, 18, 19, 20, 23, 24, 25])]