In [2]:
import numpy as np

In [3]:
A = np.arange(1,26).reshape(5,5)

In [4]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
a1 = A[0,:3]
a2 = A[1,:3]
a3 = A[2,:3]
com1 = np.concatenate([a1,a2,a3])

In [6]:
a1
a2
a3

array([11, 12, 13])

In [7]:
com1

array([ 1,  2,  3,  6,  7,  8, 11, 12, 13])

In [8]:
b1 = A[0,1:4]
b2 = A[1,1:4]
b3 = A[2,1:4]
com2 = np.concatenate([b1,b2,b3])
com2

array([ 2,  3,  4,  7,  8,  9, 12, 13, 14])

In [13]:
b1

array([2, 3, 4])

In [9]:
c1 = A[0,2:5]
c2 = A[1,2:5]
c3 = A[2,2:5]
com3 = np.concatenate([c1,c2,c3])
com3

array([ 3,  4,  5,  8,  9, 10, 13, 14, 15])

In [10]:
d1 = A[2,0:3]
d2 = A[3,0:3]
d3 = A[4,0:3]
com4 = np.concatenate([d1,d2,d3])
com4

array([11, 12, 13, 16, 17, 18, 21, 22, 23])

In [26]:
fil = 3
def split_array(A,fil):
    s = []
    length = len(A)-fil+1
    for i in range(length): # row
        for j in range(length): # col
            temp = [0]* fil
            for z in range(fil):
                temp[z] = A[i+z,j:j+fil]
            com = np.concatenate([item for item in temp ])
            s.append(com)
    return s               

In [21]:
B = np.arange(36).reshape(6,6)

In [29]:
res = split_array(B,5)
res  

[array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 18, 19,
        20, 21, 22, 24, 25, 26, 27, 28]),
 array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20,
        21, 22, 23, 25, 26, 27, 28, 29]),
 array([ 6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25,
        26, 27, 28, 30, 31, 32, 33, 34]),
 array([ 7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26,
        27, 28, 29, 31, 32, 33, 34, 35])]

In [23]:
len(A)

5