In [1]:
from scipy.io import loadmat
import numpy as np

In [3]:
input_image = loadmat('F:\data\Indian_pines_corrected.mat')['indian_pines_corrected']

In [4]:
s = input_image

In [5]:
s1 = s.transpose(2,1,0)

In [6]:
s1.shape

(200, 145, 145)

In [7]:
s2 = s1.transpose(0,2,1)

In [8]:
s2.shape

(200, 145, 145)

In [9]:
#取出第一个pixel的数据

In [12]:
s[0][0,:]

array([3172, 4142, 4506, 4279, 4782, 5048, 5213, 5106, 5053, 4750, 4816,
       4769, 4610, 4805, 4828, 4861, 4767, 4624, 4549, 4463, 4462, 4446,
       4445, 4336, 4381, 4319, 4207, 4305, 4311, 3991, 4168, 3942, 4061,
       4362, 4318, 4252, 4869, 5284, 5055, 3591, 5175, 5217, 5058, 4969,
       4721, 4291, 4555, 4886, 4868, 4806, 4783, 4811, 4709, 3903, 3795,
       3715, 2591, 2130, 2269, 2480, 3145, 3626, 4060, 4296, 4211, 4225,
       4157, 4133, 4082, 4048, 3935, 3843, 3784, 3642, 3271, 2707, 1707,
       1564, 1838, 1719, 2229, 2764, 2919, 2873, 2977, 2913, 3034, 3051,
       3124, 3101, 3033, 2713, 2740, 2947, 2706, 2834, 2856, 2683, 2400,
       2229, 1822, 1542, 1097, 1047, 1069, 1100, 1122, 1259, 1365, 1261,
       1374, 1630, 1851, 2028, 2130, 2170, 2205, 2214, 2204, 2100, 2106,
       2146, 2089, 2078, 2134, 2127, 2074, 2057, 2045, 2003, 1999, 1959,
       1924, 1883, 1843, 1781, 1716, 1698, 1645, 1540, 1410, 1294, 1131,
       1044, 1032, 1045, 1100, 1212, 1295, 1244, 11

In [14]:
np.array([s2[i][0,0]for i in range(200)])

array([3172, 4142, 4506, 4279, 4782, 5048, 5213, 5106, 5053, 4750, 4816,
       4769, 4610, 4805, 4828, 4861, 4767, 4624, 4549, 4463, 4462, 4446,
       4445, 4336, 4381, 4319, 4207, 4305, 4311, 3991, 4168, 3942, 4061,
       4362, 4318, 4252, 4869, 5284, 5055, 3591, 5175, 5217, 5058, 4969,
       4721, 4291, 4555, 4886, 4868, 4806, 4783, 4811, 4709, 3903, 3795,
       3715, 2591, 2130, 2269, 2480, 3145, 3626, 4060, 4296, 4211, 4225,
       4157, 4133, 4082, 4048, 3935, 3843, 3784, 3642, 3271, 2707, 1707,
       1564, 1838, 1719, 2229, 2764, 2919, 2873, 2977, 2913, 3034, 3051,
       3124, 3101, 3033, 2713, 2740, 2947, 2706, 2834, 2856, 2683, 2400,
       2229, 1822, 1542, 1097, 1047, 1069, 1100, 1122, 1259, 1365, 1261,
       1374, 1630, 1851, 2028, 2130, 2170, 2205, 2214, 2204, 2100, 2106,
       2146, 2089, 2078, 2134, 2127, 2074, 2057, 2045, 2003, 1999, 1959,
       1924, 1883, 1843, 1781, 1716, 1698, 1645, 1540, 1410, 1294, 1131,
       1044, 1032, 1045, 1100, 1212, 1295, 1244, 11

In [15]:
np.array([s1[i][0,0]for i in range(200)])

array([3172, 4142, 4506, 4279, 4782, 5048, 5213, 5106, 5053, 4750, 4816,
       4769, 4610, 4805, 4828, 4861, 4767, 4624, 4549, 4463, 4462, 4446,
       4445, 4336, 4381, 4319, 4207, 4305, 4311, 3991, 4168, 3942, 4061,
       4362, 4318, 4252, 4869, 5284, 5055, 3591, 5175, 5217, 5058, 4969,
       4721, 4291, 4555, 4886, 4868, 4806, 4783, 4811, 4709, 3903, 3795,
       3715, 2591, 2130, 2269, 2480, 3145, 3626, 4060, 4296, 4211, 4225,
       4157, 4133, 4082, 4048, 3935, 3843, 3784, 3642, 3271, 2707, 1707,
       1564, 1838, 1719, 2229, 2764, 2919, 2873, 2977, 2913, 3034, 3051,
       3124, 3101, 3033, 2713, 2740, 2947, 2706, 2834, 2856, 2683, 2400,
       2229, 1822, 1542, 1097, 1047, 1069, 1100, 1122, 1259, 1365, 1261,
       1374, 1630, 1851, 2028, 2130, 2170, 2205, 2214, 2204, 2100, 2106,
       2146, 2089, 2078, 2134, 2127, 2074, 2057, 2045, 2003, 1999, 1959,
       1924, 1883, 1843, 1781, 1716, 1698, 1645, 1540, 1410, 1294, 1131,
       1044, 1032, 1045, 1100, 1212, 1295, 1244, 11

In [16]:
# 第二个pixel
s[0][1,:]

array([2580, 4266, 4502, 4426, 4853, 5249, 5352, 5353, 5347, 5065, 5141,
       5100, 4994, 5172, 5290, 5289, 5217, 5053, 5033, 4939, 4931, 4941,
       4902, 4824, 4859, 4805, 4698, 4794, 4806, 4452, 4628, 4433, 4643,
       4967, 4853, 4760, 5449, 5768, 5684, 3987, 5773, 5789, 5607, 5585,
       5165, 4720, 5019, 5387, 5301, 5304, 5254, 5291, 5165, 4282, 4149,
       4014, 3656, 2277, 2430, 2632, 2627, 3929, 4383, 4649, 4551, 4557,
       4472, 4468, 4398, 4361, 4185, 4149, 4067, 3931, 2736, 2856, 1761,
       1635, 1892, 1779, 2340, 2905, 3070, 3058, 3131, 3078, 3183, 3259,
       2574, 3315, 3214, 2841, 2951, 3133, 2842, 3028, 3038, 2842, 2550,
       2359, 1916, 1615, 1118, 1036, 1071, 1110, 1128, 1276, 1388, 1284,
       1406, 1675, 1927, 2106, 2229, 2270, 2301, 2326, 2303, 2195, 2195,
       2228, 2175, 2165, 2215, 2210, 2151, 2135, 2127, 2090, 2072, 2038,
       1998, 1947, 1909, 1837, 1781, 1750, 1700, 1580, 1435, 1325, 1152,
       1059, 1030, 1045, 1114, 1232, 1314, 1262, 10

In [17]:
np.array([s2[i][0,1]for i in range(200)])

array([2580, 4266, 4502, 4426, 4853, 5249, 5352, 5353, 5347, 5065, 5141,
       5100, 4994, 5172, 5290, 5289, 5217, 5053, 5033, 4939, 4931, 4941,
       4902, 4824, 4859, 4805, 4698, 4794, 4806, 4452, 4628, 4433, 4643,
       4967, 4853, 4760, 5449, 5768, 5684, 3987, 5773, 5789, 5607, 5585,
       5165, 4720, 5019, 5387, 5301, 5304, 5254, 5291, 5165, 4282, 4149,
       4014, 3656, 2277, 2430, 2632, 2627, 3929, 4383, 4649, 4551, 4557,
       4472, 4468, 4398, 4361, 4185, 4149, 4067, 3931, 2736, 2856, 1761,
       1635, 1892, 1779, 2340, 2905, 3070, 3058, 3131, 3078, 3183, 3259,
       2574, 3315, 3214, 2841, 2951, 3133, 2842, 3028, 3038, 2842, 2550,
       2359, 1916, 1615, 1118, 1036, 1071, 1110, 1128, 1276, 1388, 1284,
       1406, 1675, 1927, 2106, 2229, 2270, 2301, 2326, 2303, 2195, 2195,
       2228, 2175, 2165, 2215, 2210, 2151, 2135, 2127, 2090, 2072, 2038,
       1998, 1947, 1909, 1837, 1781, 1750, 1700, 1580, 1435, 1325, 1152,
       1059, 1030, 1045, 1114, 1232, 1314, 1262, 10

In [20]:
np.array([s1[i][1,0]for i in range(200)])

array([2580, 4266, 4502, 4426, 4853, 5249, 5352, 5353, 5347, 5065, 5141,
       5100, 4994, 5172, 5290, 5289, 5217, 5053, 5033, 4939, 4931, 4941,
       4902, 4824, 4859, 4805, 4698, 4794, 4806, 4452, 4628, 4433, 4643,
       4967, 4853, 4760, 5449, 5768, 5684, 3987, 5773, 5789, 5607, 5585,
       5165, 4720, 5019, 5387, 5301, 5304, 5254, 5291, 5165, 4282, 4149,
       4014, 3656, 2277, 2430, 2632, 2627, 3929, 4383, 4649, 4551, 4557,
       4472, 4468, 4398, 4361, 4185, 4149, 4067, 3931, 2736, 2856, 1761,
       1635, 1892, 1779, 2340, 2905, 3070, 3058, 3131, 3078, 3183, 3259,
       2574, 3315, 3214, 2841, 2951, 3133, 2842, 3028, 3038, 2842, 2550,
       2359, 1916, 1615, 1118, 1036, 1071, 1110, 1128, 1276, 1388, 1284,
       1406, 1675, 1927, 2106, 2229, 2270, 2301, 2326, 2303, 2195, 2195,
       2228, 2175, 2165, 2215, 2210, 2151, 2135, 2127, 2090, 2072, 2038,
       1998, 1947, 1909, 1837, 1781, 1750, 1700, 1580, 1435, 1325, 1152,
       1059, 1030, 1045, 1114, 1232, 1314, 1262, 10